source 'https://github.com/igagis/cocoapods-repo.git'

project 'setka/setka.xcodeproj'

platform :ios, '8.0'

target "%name%" do
	pod 'utki', '>= 1.1.30'
	pod 'opros', '>= 1.0.28'
	pod 'nitki', '>= 1.0.14'
	pod 'papki', '>= 1.0.58'
end
