source 'https://github.com/cppfw/cocoapods-repo.git'

project 'setka/setka.xcodeproj'

platform :ios, '9.0'

target "setka" do
	pod 'utki', '>= 1.1.124'
	pod 'opros', '>= 1.0.46'
	pod 'nitki', '>= 1.0.41'
	pod 'papki', '>= 1.0.93'
end
